### ISSUE TITLE
No module named blackdog

### ISSUE THREAD

**Issue by pieterhouwen** [darkcode357/blackdogosint#453]
After poetry install I get the following errors:

![image](https://user-images.githubusercontent.com/10866686/124608492-12053780-de6f-11eb-8d97-59b40830977d.png)

**Comment by darkcode357** [comment]
if you look in the photo you posted the name of the installed module is blackdogosint and not blackdog, to check this information and just give an ls in the directory.

I would like your contribution to improve the project.
by darkcode0x00

try 
![image](https://user-images.githubusercontent.com/24551924/124860614-4fa9b380-df88-11eb-875b-82ccc80a8e83.png)
![image](https://user-images.githubusercontent.com/24551924/124860670-6a7c2800-df88-11eb-9fa7-ada50d5742a0.png)

**Comment by pieterhouwen** [comment]
You then may want to update your README.md because there the command is listed as "Import blackdog".

When following your example and trying to autocomplete from "blackdogosint." I'm not getting the same result as you:

```
>>> blackdogosint.__
blackdogosint.__cached__          blackdogosint.__gt__(             blackdogosint.__path__
blackdogosint.__class__(          blackdogosint.__hash__(           blackdogosint.__reduce__(
blackdogosint.__delattr__(        blackdogosint.__init__(           blackdogosint.__reduce_ex__(
blackdogosint.__dict__            blackdogosint.__init_subclass__(  blackdogosint.__repr__(
blackdogosint.__dir__(            blackdogosint.__le__(             blackdogosint.__setattr__(
blackdogosint.__doc__             blackdogosint.__loader__          blackdogosint.__sizeof__(
blackdogosint.__eq__(             blackdogosint.__lt__(             blackdogosint.__spec__
blackdogosint.__file__            blackdogosint.__name__            blackdogosint.__str__(
blackdogosint.__format__(         blackdogosint.__ne__(             blackdogosint.__subclasshook__(
blackdogosint.__ge__(             blackdogosint.__new__(            blackdogosint.__version__
blackdogosint.__getattribute__(   blackdogosint.__package__
>>> blackdogosint.__
```

Even when I try to install it using pip3 instead of using poetry I'm not getting the submodules.

Regarding your question for me to help, I'm not sure if I can actually help you because I don't know python at all.

**Comment by darkcode357** [comment]
you can leave, I will check the error and soon I will fix it, I'm doing the implementation to generate reports automaticallymanete through the blackdogreport lib.

due to this reason I can't fix the error yet, this should be something in __init__, following the new check model I implemented in pre_commit

**Comment by darkcode357** [comment]
![image](https://user-images.githubusercontent.com/24551924/125154035-52460d80-e12e-11eb-9b37-23ed7dfcf473.png)
![image](https://user-images.githubusercontent.com/24551924/125154051-5d00a280-e12e-11eb-939d-2ff17c8442cd.png)
![image](https://user-images.githubusercontent.com/24551924/125154356-07c59080-e130-11eb-951b-ae463495ece7.png)
![image](https://user-images.githubusercontent.com/24551924/125154367-11e78f00-e130-11eb-949f-81f26243fd7c.png)
![image](https://user-images.githubusercontent.com/24551924/125154379-1f047e00-e130-11eb-99b0-36668ecd50e3.png)
![image](https://user-images.githubusercontent.com/24551924/125154387-27f54f80-e130-11eb-9bdf-d98d4dd1f4f1.png)
all fxd

**Comment by darkcode357** [comment]
![image](https://user-images.githubusercontent.com/24551924/125154966-35600900-e133-11eb-8ee5-487f2573feca.png)
